### ISSUE TITLE
Mssing bits: high-load-stress-8.3.0.jar

### ISSUE THREAD

**Issue by arth2o** [hogejo/high-load-stress#3]
Valahogy nem teljes ez a leírás hogy kell ezt használni.
Szerintem hiányzik belőle néhány fálj vagy leírás hogyan tudom előálítani azokat a fáljokat a meglévő adatokból.

**Comment by arth2o** [comment]
https://github.com/hogejo/high-load-stress/releases/tag/v8.3.0

**Comment by hogejo** [comment]
Arra gondolsz, hogyan lehet build-elni forráskódból?
Vagy a linkelt release-ből hiányzik valami? Milyen fájlokat próbálsz előállítani?

**Comment by arth2o** [comment]
Köszi! Közben megtalltam amit kerestem a linken.
